services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "7869:11434"
    volumes:
      - ./ollama/ollama:/root/.ollama
      - ./init-ollama.sh:/init-ollama.sh
    container_name: ollama
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    entrypoint: ["/init-ollama.sh"] 
    networks:
      - ollama-docker


  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    volumes:
      - ./ollama/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 8088:8080
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - OLLAMA_BASE_URLS=http://ollama:11434
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=AI
      - WEBUI_URL=http://localhost:8080
      - WEBUI_SECRET_KEY=t0p-s3cr3t
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - ollama-docker

  # flask:
  #   container_name: flask
  #   build:
  #     context: ./app
  #     dockerfile: ./Dockerfile
  #     target: ${ENV}
  #   ports:
  #     - "5000:5000"
  #     - "5678:5678"
  #   volumes:
  #     - ./app:/app
  #   env_file:
  #     - .env
  #   networks:
  #     - ollama-docker

networks:
  ollama-docker:
    external: false
